[package]
authors = ["Sebastian <sb@pus.de>", "Marius <mariusdieckmann90@gmail.com>"]
description = "The Rust API build for the Aruna Object Storage (AOS)"
edition = "2021"
license = "Apache-2.0"
name = "aruna-rust-api"
version = "1.0.0-rc.5"
include = ["src"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost = "0.11.0"
prost-types = "0.11.0"
serde = "1.0"
serde_json = "1.0"
tonic = "0.8.2"

[build-dependencies]
tonic-build = "0.8.2"