[package]
authors = ["Marius <mariusdieckmann90@gmail.com>"]
description = "The Rust API build for the ScienceObjectsDB"
edition = "2018"
license-file = "LICENSE"
name = "scienceobjectsdb_rust_api"
version = "0.3.0-alpha.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost = "0"
prost-derive = "0"
prost-types = "0"
serde = "1"
serde_json = "1"
tonic = "0"

[build-dependencies]
tonic-build = "0"
