[package]
name = "scienceobjectsdb_rust_api"
version = "0.1.0-alpha.1"
authors = ["Marius <mariusdieckmann90@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tonic = "0.5"
prost = "0.8"
prost-types = "0.8"
prost-derive = "0.8"
serde = "1"
serde_json = "1"

[build-dependencies]
tonic-build = "0.5"