[package]
authors = ["Sebastian <sb@pus.de>", "Marius <mariusdieckmann90@gmail.com>"]
description = "The Rust API build for the Aruna Object Storage (AOS)"
edition = "2021"
license = "Apache-2.0"
name = "aruna-rust-api"
version = "1.1.0-rc.3"
include = ["src"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost = "0.11.8"
prost-types = "0.11.8"
serde = "1.0.159"
serde_json = "1.0.95"
tonic = {version="0.9.1", default-features = false, features=["codegen", "prost"]}

[build-dependencies]
tonic-build = "0.9.1"

[features]
default = ["transport"]
transport = ["tonic/transport"]