[package]
authors = ["Sebastian <sb@pus.de>", "Marius <mariusdieckmann90@gmail.com>"]
description = "The Rust API build for the Aruna Object Storage (AOS)"
edition = "2018"
license-file = "LICENSE"
name = "aruna-rust-api"
version = "0.4.1-alpha.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost = "0"
prost-derive = "0"
prost-types = "0"
serde = "1"
serde_json = "1"
tonic = "0"

[build-dependencies]
tonic-build = "0"
