name: test_build_pull_request
on:
  push:
    tags:
      - '*'
jobs:
  lint: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout without submodules
        uses: actions/checkout@v2
      - name: Setup buf
        uses: bufbuild/buf-setup-action@v1
      - name: Lint protofiles with buf
        uses: bufbuild/buf-lint-action@v1
  build: # This does not build the whole proto files for production, it tests if rust / tonic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Pull rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Test compiling protofiles with rust
        uses: actions-rs/cargo@v1
        with:
          command: cargo build
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Cargo publish    
        run: cargo publish --token ${CRATES_TOKEN}
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
          CARGO_PKG_VERSION: ${{ env.RELEASE_VERSION }}