name: test_build_pull_request
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Pull rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Test compiling protofiles with rust
        uses: actions-rs/cargo@v1
        with:
          command: cargo build
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Cargo publish    
        run: cargo publish --token ${CRATES_TOKEN}
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
          CARGO_PKG_VERSION: ${{ env.RELEASE_VERSION }}